- name: Variables and facts demo
  hosts: localhost
  become: yes
  vars_files:
    - vars/common.yml
  tasks:
    - name: Print a greeting
      debug:
        msg: "{{ greeting }}"

    - name: Create a file using variables
      copy:
        content: "{{ greeting }}"
        dest: "{{ file_path }}"

    - name: Show system facts
      debug:
        var: ansible_facts
