- name: My first Ansible playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Install htop
      apt:
        name: htop
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Create a hello file
      copy:
        content: "Hello from Ansible!"
        dest: /tmp/hello.txt

